<!DOCTYPE html>
<html>
<title>Intacct Office matrix</title>
<body>
<hr/>
<?php
foreach ($data as $key => $element) {
    echo "Label : ".$key . "<br><br/>";
    echo "Average distance : {$element['display_averageDistanceValue']}<br/>";
    echo "Average duration : {$element['display_averageDurationValue']}<br/>";
    echo "Average duration (of executed time): {$element['display_averageTrafficDurationValue']}<br/>";
    echo "<hr/>";
}
?>
<hr/>

</body>
</html>