<!DOCTYPE html>
<html>
<title>Intacct Office matrix</title>
<body>

<script>
    <?php
    switch ($responseKey) {
        case 1:
            echo "alert('Record added!');";
            break;
        case -1:
            echo "alert('Only aplha allowed in Labels');";
            break;
    }
    ?>
</script>

<form action="<?php echo MyURL::generate("setDetails") ?>" method="post">
    <label>Label Name :</label>
    <input name="label"/><br/><br/>
    <label>Destination :</label>
    <input name="destination"/><br/><br/>
    <label>Origins (one in each line)</label><br/>
    <textarea name="origins" rows="25"></textarea><br/><br/>
    <input type="submit" />
</form>
</body>
</html>